### ISSUE TITLE
Access the server response 

### ISSUE THREAD

**Issue by ranocohen** [PCreations/RESTDroid#1]
Hi,

In onFinishedRequest, how should I implement this.getResultStream()?

Following your simple example (which getResultStream not implemented there) I get this:

The method getResultStream() is undefined for the type new RequestListeners.OnFinishedRequestListener(){}

**Comment by PCreations** [comment]
Hi,

According to documentation, getResultStream is a method of RESTRequest class, since RequestListeners class is holding a reference to the request via the member field "mRequest" you can access the result stream by calling in your OnFinishedRequestListener : 

mRequest.getResultStream();
